// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFCeQybYQpBN2FnupUaKrIGNZZ7y6nduY',
    appId: '1:437797410523:web:d20d7cec00c8fb27ff5efe',
    messagingSenderId: '437797410523',
    projectId: 'glean-cookbook',
    authDomain: 'glean-cookbook.firebaseapp.com',
    storageBucket: 'glean-cookbook.appspot.com',
    measurementId: 'G-D7Q8ZH35FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Pd2d4wDU6aL3whmLpnwBdcidarSgDtc',
    appId: '1:437797410523:android:e33bacfec13c5b5bff5efe',
    messagingSenderId: '437797410523',
    projectId: 'glean-cookbook',
    storageBucket: 'glean-cookbook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEIhtLdIzrxEIcCLW-ksMf365-VPeDBhQ',
    appId: '1:437797410523:ios:e00ac688132d8c89ff5efe',
    messagingSenderId: '437797410523',
    projectId: 'glean-cookbook',
    storageBucket: 'glean-cookbook.appspot.com',
    androidClientId: '437797410523-3b65f4e6vp8hkoo3lkr2r2jfeh0ii8mi.apps.googleusercontent.com',
    iosClientId: '437797410523-c0saavb5a47eoj0d0ce6v3uot9r97hr3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gleanCookbook',
  );
}
